<?php

namespace app\admin\controller;

use think\Controller;
use think\Request;

class Base extends Controller
{
    /**
     * 基础控制器初始化
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        // 获取当前模块、控制器、方法
        $request = Request::instance();
        $module = $request->module();
        $controller = $request->controller();
        $action = $request->action();
        //halt($controller);
        $this->assign('cont',$controller);
    }
}
