<?php

namespace app\admin\controller;

use houdunwang\arr\Arr;
use think\Controller;
use think\Request;

class Base extends Controller
{
    /**
     * 基础控制器初始化
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        // 获取当前模块、控制器、方法
        $route = strtolower($this->getRouter());
        // 侧边栏菜单
        $menu = $this->leftMenu();
        $this->assign('menu', $menu);
        $this->assign('route', $route);
    }

    public function leftMenu ()
    {
        // 获取侧边栏数据
        $data = db('menu')->select();
        $menus = Arr::channelList($data, $pid = 0, $html = "", 'menu_id', 'menu_pid');
        return $menus;
    }

    /**
     * 获取当前路由
     * @return string
     */
    public function getRouter()
    {
        // 获取当前模块、控制器、方法
        $request = Request::instance();
        $module = $request->module();
        $controller = $request->controller();
        $action = $request->action();
        // $router = $module . '/' . $controller . '/' . $action;
        $router = $controller;
        return $router;
    }
}
